"""First migration

Revision ID: 0001
Revises: 
Create Date: 2023-07-03 22:00:00.128440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iban',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('valid', 'invalid', name='iban_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_iban_iban'), 'iban', ['iban'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iban_iban'), table_name='iban')
    op.drop_table('iban')
    # ### end Alembic commands ###
